auto: true

markdown: kramdown
kramdown:
    input: GFM
rouge: true
permalink: /:title

title: Be a better man
url: sharethetime.win
feed: /atom.xml
author_info: <a href="sharethetime.win">MadaoNo</a>
